Repository eslint/markdown, pull requests merged in 2018-04, with the labels that each got.

#90 Chore: Add .npmrc to disable creating package-lock.json
  .npmrc
Labels: accepted, infrastructure

#91 Docs: Add unicode-bom to list of unsatisfiable rules
  README.md
Labels: accepted

#92 Build: Upgrade to eslint-release@0.11.1
  package.json
Labels: accepted, infrastructure

#93 Docs: Updating CLA link
  CONTRIBUTING.md
Labels: triage
