Repository eslint/markdown, pull requests merged in 2019-10, with the labels that each got.

#119 Fix: Support autofix at the very start of blocks
  lib/processor.js
  tests/lib/plugin.js
Labels: accepted, bug

#122 Chore: Add Node 12 to Travis
  .travis.yml
Labels: accepted, chore

#123 Chore: Use GitHub Actions
  .github/workflows/ci.yml
Labels: chore

#124 Fix: Indent multiline fixes (fixes #120)
  lib/processor.js
  tests/lib/plugin.js
Labels: bug
