Repository eslint/markdown, pull requests merged in 2020-08, with the labels that each got.

#154 Fix: Don't require message end locations (fixes #112)
  lib/processor.js
  tests/lib/plugin.js
Labels: accepted, bug

#153 New: Add recommended config (fixes #151)
  README.md
  index.js
  lib/index.js
  tests/fixtures/recommended.json
  tests/lib/plugin.js
Labels: accepted, enhancement

#152 Docs: Add React example
  .eslintrc.js
  .github/workflows/ci.yml
  examples/react/.eslintrc.js
  examples/react/.npmrc
  examples/react/README.md
  examples/react/package.json
  package.json
  tests/examples/all.js
Labels: accepted, documentation

#158 Chore: run CI in Node 14.x
  .github/workflows/ci.yml
Labels: chore

#157 New: Add recommended config
  lib/index.js
Labels: accepted, enhancement

#155 Docs: Add TypeScript example
  .github/workflows/ci.yml
  examples/typescript/.eslintrc.js
  examples/typescript/.npmrc
  examples/typescript/README.md
  examples/typescript/package.json
Labels: accepted, documentation

#159 Docs: Reference recommended config disabled rules
  README.md
  lib/index.js
Labels: accepted, documentation

#160 Build: Install example test dependencies in Jenkins
  .github/workflows/ci.yml
  package.json
Labels: accepted, bug, infrastructure
