Repository eslint/markdown, pull requests merged in 2021-03, with the labels that each got.

#177 Fix: More reliable comment attachment (fixes #76)
  lib/processor.js
  tests/lib/processor.js
Labels: accepted, bug

#182 Docs: improve jsdoc, better for typings
  lib/processor.js
Labels: accepted, documentation

#184 Chore: add yarn.lock and package-lock.json into .gitignore just like eslint/eslint
  .gitignore
Labels: triage
