Repository eslint/markdown, pull requests merged in 2021-11, with the labels that each got.

#196 chore: test all supported ESLint versions
  .github/workflows/ci.yml
Labels: accepted, chore

#197 chore: update `devDependencies`
  .eslintrc.js
  package.json
Labels: accepted, chore

#199 ci: use node `v16`
  .github/workflows/ci.yml
Labels: triage

#198 test: test with `ESLint` instead of `CLIEngine` when available
  tests/lib/plugin.js
Labels: accepted, chore

#200 chore: Check for package.json in examples
  npm-prepare.js
  tests/examples/all.js
Labels: chore

#195 chore: add tests for ESLint 8
  .github/workflows/ci.yml
  package.json
Labels: triage
