Repository eslint/markdown, pull requests merged in 2024-11, with the labels that each got.

#298 chore: mdast-util-from-markdown ^2.0.2
  package.json
Labels: chore

#302 test: Update tests for ESLint v9.15.0
  examples/typescript/package.json
  package.json
  tests/plugin.test.js
Labels: accepted, chore

#301 chore: upgrade @eslint/plugin-kit@0.2.3
  package.json
Labels: chore

#304 chore: use eslint-plugin-eslint-plugin
  README.md
  eslint.config.js
  package.json
  src/rules/fenced-code-language.js
  src/rules/heading-increment.js
  src/rules/no-duplicate-headings.js
  src/rules/no-empty-links.js
  src/rules/no-html.js
  src/rules/no-invalid-label-refs.js
  src/rules/no-missing-label-refs.js
Labels: chore

#303 test: unpin `eslint` in `typescript-eslint` test
  examples/typescript/package.json
Labels: chore

#305 fix: add type tests
  .github/workflows/ci.yml
  package.json
  src/index.js
  tests/types/tsconfig.json
  tests/types/types.test.ts
  tools/build-rules.js
Labels: bug
