Repository eslint/markdown, pull requests merged in 2024-09, with the labels that each got.

#279 fix: correct `exports` field in package.json
  package.json
Labels: bug

#280 refactor: Use @eslint/plugin-kit
  eslint.config.js
  package.json
  src/language/markdown-source-code.js
Labels: accepted, chore

#282 fix: Account for BOM in the processor
  src/processor.js
  tests/processor.test.js
Labels: bug

#285 docs: Fix example with individually configured rules
  README.md
Labels: documentation
