Repository eslint/markdown, pull requests merged in 2024-02, with the labels that each got.

#234 chore: remove unused `@eslint/eslintrc` in test examples
  examples/react/eslint.config.js
  examples/react/package.json
Labels: chore

#235 test: use latest `typescript-eslint` in examples
  examples/typescript/README.md
  examples/typescript/eslint.config.js
  examples/typescript/package.json
Labels: chore

#233 feat: add `meta` property
  lib/index.js
  lib/processor.js
  tests/lib/plugin.js
  tests/lib/processor.js
Labels: accepted, feature

#236 chore: add `.vscode` to `.gitignore`
  .gitignore
Labels: chore

#237 docs: fix expected errors in react example
  examples/react/README.md
Labels: documentation

#238 feat!: drop eslint < 8 & Node.js < 18
  .github/workflows/ci.yml
  README.md
  package.json
Labels: breaking, feature
