Repository eslint/markdown, pull requests merged in 2024-08, with the labels that each got.

#266 feat: Add type checking and type definitions
  .gitignore
  package.json
  rollup.config.js
  src/index.js
  src/processor.js
  src/types.ts
  tools/dedupe-types.js
  tsconfig.esm.json
  tsconfig.json
Labels: feature

#268 feat: Add Markdown languages
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/change.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/new-rule.yml
  .github/ISSUE_TEMPLATE/rule-change.yml
  .gitignore
  README.md
  docs/processors/markdown.md
  docs/rules/fenced-code-language.md
  docs/rules/heading-increment.md
  docs/rules/no-duplicate-headings.md
  docs/rules/no-empty-links.md
  docs/rules/no-html.md
  docs/rules/no-invalid-label-refs.md
  docs/rules/no-missing-label-refs.md
  eslint.config-content.js
  eslint.config.js
  examples/react/eslint.config.mjs
  examples/typescript/eslint.config.mjs
  package.json
  src/index.js
  src/language/markdown-language.js
  src/language/markdown-source-code.js
  src/rules/fenced-code-language.js
  src/rules/heading-increment.js
  src/rules/no-duplicate-headings.js
  src/rules/no-empty-links.js
  src/rules/no-html.js
  src/rules/no-invalid-label-refs.js
  src/rules/no-missing-label-refs.js
  src/types.ts
  src/util.js
  tests/fixtures/recommended.js
  tests/language/markdown-source-code.test.js
  tests/rules/fenced-code-language.test.js
  tests/rules/heading-increment.test.js
  tests/rules/no-duplicate-headings.test.js
  tests/rules/no-empty-links.test.js
  tests/rules/no-html.test.js
  tests/rules/no-invalid-label-refs.test.js
  tests/rules/no-missing-label-refs.test.js
  tools/build-rules.js
Labels: accepted, feature

#270 chore: Enable Prettier
  .github/workflows/add-to-triage.yml
  .github/workflows/ci.yml
  .github/workflows/release-please.yml
  .prettierignore
  eslint.config-content.js
  eslint.config.js
  examples/react/eslint.config.mjs
  examples/typescript/eslint.config.mjs
  npm-prepare.cjs
  package.json
  prettier.config.js
  release-please-config.json
  rollup.config.js
  src/index.js
  src/language/markdown-language.js
  src/language/markdown-source-code.js
  src/processor.js
  src/rules/fenced-code-language.js
  src/rules/heading-increment.js
  src/rules/no-duplicate-headings.js
  src/rules/no-empty-links.js
  src/rules/no-html.js
  src/rules/no-invalid-label-refs.js
  src/rules/no-missing-label-refs.js
  src/types.ts
  src/util.js
  tests/examples/all.test.js
  tests/fixtures/eslint.config.js
  tests/fixtures/eslintrc.json
  tests/fixtures/recommended.js
  tests/fixtures/recommended.json
  tests/language/markdown-source-code.test.js
  tests/plugin.test.js
  tests/processor.test.js
  tests/rules/fenced-code-language.test.js
  tests/rules/heading-increment.test.js
  tests/rules/no-duplicate-headings.test.js
  tests/rules/no-empty-links.test.js
  tests/rules/no-html.test.js
  tests/rules/no-invalid-label-refs.test.js
  tests/rules/no-missing-label-refs.test.js
  tools/build-rules.js
  tools/dedupe-types.js
Labels: chore

#271 feat: JSR package
  .github/workflows/ci.yml
  .github/workflows/release-please.yml
  jsr.json
  package.json
  release-please-config.json
Labels: accepted, feature

#274 docs: update rules table during build
  README.md
  package.json
  tools/update-rules-docs.js
Labels: documentation
