Repository eslint/markdown, pull requests merged in 2024-10, with the labels that each got.

#281 feat: Add disable comment support
  README.md
  package.json
  src/language/markdown-source-code.js
  src/rules/no-html.js
  tests/language/markdown-source-code.test.js
  tests/plugin.test.js
  tests/rules/no-html.test.js
Labels: accepted, feature

#287 docs: Add sponsors to README
  .github/workflows/update-readme.yml
  README.md
  package.json
  tools/commit-readme.sh
  tools/update-readme.js
Labels: accepted, documentation

#291 chore: Update comments to correctly refer to MarkdownSourceCode
  src/language/markdown-language.js
Labels: chore, documentation

#290 fix: no-missing-label-refs should not crash on undefined labels
  src/rules/no-missing-label-refs.js
  src/util.js
  tests/rules/no-missing-label-refs.test.js
Labels: bug, accepted

#295 test: Use latest `typescript-eslint` v8.x
  examples/typescript/package.json
Labels: chore

#296 ci: add Node.js v23
  .github/workflows/ci.yml
Labels: build
