Repository eslint/markdown, pull requests merged in 2024-04, with the labels that each got.

#247 fix: check upper bounds of message line numbers for code blocks
  lib/processor.js
  tests/lib/processor.js
Labels: bug, accepted, contributor pool

#246 feat!: map known code block languages to respective file extensions
  README.md
  eslint.config.js
  lib/processor.js
  tests/lib/processor.js
Labels: accepted, breaking, feature, contributor pool

#250 ci: run tests in Node.js 22, with ESLint 9
  .github/workflows/ci.yml
Labels: accepted, build
