Repository eslint/markdown, pull requests merged in 2024-07, with the labels that each got.

#256 feat: add name to flat configs
  lib/index.js
Labels: feature

#258 build: Update release-please
  .github/workflows/release-please.yml
  .release-please-manifest.json
  lib/index.js
  lib/processor.js
  release-please-config.json
Labels: build

#262 build: Fix release-please tag name
  release-please-config.json
Labels: build

#259 feat!: Convert to ESM
  .github/workflows/ci.yml
  .github/workflows/release-please.yml
  README.md
  eslint.config.js
  examples/react/eslint.config.mjs
  examples/typescript/eslint.config.mjs
  index.js
  npm-prepare.cjs
  package.json
  release-please-config.json
  src/index.js
  src/processor.js
  tests/examples/all.test.js
  tests/fixtures/eslint.config.js
  tests/fixtures/recommended.js
  tests/plugin.test.js
  tests/processor.test.js
Labels: accepted, breaking, feature

#264 test: use ESLint v9 in examples
  examples/react/README.md
  examples/react/eslint.config.mjs
  examples/react/package.json
  examples/typescript/README.md
  examples/typescript/eslint.config.mjs
  examples/typescript/package.json
  tests/examples/all.test.js
Labels: chore

#265 feat!: Rename to @eslint/markdown
  .github/workflows/release-please.yml
  CONTRIBUTING.md
  LICENSE
  README.md
  eslint.config.js
  examples/react/README.md
  examples/typescript/README.md
  package.json
  src/index.js
  src/processor.js
  tests/plugin.test.js
  tests/processor.test.js
Labels: accepted, breaking, feature
