Repository eslint/markdown, pull requests merged in 2025-06, with the labels that each got.

#392 feat: added new rule table-column-count
  README.md
  docs/rules/table-column-count.md
  src/rules/table-column-count.js
  tests/rules/table-column-count.test.js
Labels: accepted, feature, contributor pool

#400 ci: create `ci-build-all-pm.yml`
  .github/workflows/ci-build-all-pm.yml
Labels: build

#407 docs: fix minor typos
  docs/rules/no-duplicate-definitions.md
  docs/rules/no-multiple-h1.md
Labels: accepted, documentation

#393 feat: add checkSiblingsOnly option to no-duplicate-headings rule
  docs/rules/no-duplicate-headings.md
  src/rules/no-duplicate-headings.js
  tests/rules/no-duplicate-headings.test.js
Labels: accepted, feature, contributor pool

#411 feat: add JSON frontmatter support
  README.md
  src/language/markdown-language.js
  src/types.ts
  tests/language/markdown-language.test.js
  tests/types/types.test.ts
Labels: accepted, feature, contributor pool

#420 test: add test for `findOffsets()` util
  tests/util.test.js
Labels: chore

#413 feat: update `no-multiple-h1` rule to recognize JSON frontmatter
  docs/rules/no-multiple-h1.md
  src/rules/no-multiple-h1.js
  tests/rules/no-multiple-h1.test.js
Labels: accepted, feature

#426 chore: update lint-staged to run `git add README.md` when rules change
  package.json
Labels: chore

#418 feat: add no-bare-urls rule
  README.md
  docs/rules/no-bare-urls.md
  src/rules/no-bare-urls.js
  tests/rules/no-bare-urls.test.js
Labels: accepted, feature, contributor pool

#431 test: correct indentation in `fenced-code-language` test cases
  tests/rules/fenced-code-language.test.js
Labels: chore

#438 fix: update `no-duplicate-headings` to align with CommonMark spec
  src/rules/no-duplicate-headings.js
  tests/rules/no-duplicate-headings.test.js
Labels: bug, accepted

#445 fix: skip HTML nodes in heading slugs for no-missing-link-fragments
  docs/rules/no-missing-link-fragments.md
  src/rules/no-missing-link-fragments.js
  tests/rules/no-missing-link-fragments.test.js
Labels: bug, accepted, contributor pool

#437 fix: handle URL-encoded link fragments in no-missing-link-fragments rule
  docs/rules/no-missing-link-fragments.md
  src/rules/no-missing-link-fragments.js
  tests/rules/no-missing-link-fragments.test.js
Labels: bug, contributor pool
