Repository eslint/markdown, pull requests merged in 2025-03, with the labels that each got.

#318 feat: allow specifying filename in block meta
  README.md
  src/processor.js
  src/types.ts
  tests/fixtures/filename.md
  tests/plugin.test.js
  tests/processor.test.js
Labels: accepted, feature

#322 docs: Remove Atom
  README.md
Labels: documentation

#324 fix: provide a language-specific definition for `RuleModule`
  package.json
  src/index.js
  src/language/markdown-source-code.js
  src/rules/fenced-code-language.js
  src/rules/heading-increment.js
  src/rules/no-duplicate-headings.js
  src/rules/no-empty-links.js
  src/rules/no-html.js
  src/rules/no-invalid-label-refs.js
  src/rules/no-missing-label-refs.js
  src/types.ts
  tests/types/types.test.ts
  tools/dedupe-types.js
Labels: bug, accepted

#329 test: create tests for `MarkdownLanguage`
  tests/language/markdown-language.test.js
Labels: chore
