Repository eslint/markdown, pull requests merged in 2025-08, with the labels that each got.

#497 ci: centralize `add-to-triage.yml`
  .github/workflows/add-to-triage.yml
Labels: accepted, build

#488 fix: normalize definition identifiers in no-*-definitions rules
  package.json
  src/rules/no-duplicate-definitions.js
  src/rules/no-empty-definitions.js
  src/rules/no-unused-definitions.js
  tests/rules/no-duplicate-definitions.test.js
  tests/rules/no-empty-definitions.test.js
  tests/rules/no-unused-definitions.test.js
Labels: bug, accepted

#495 refactor: simplify `no-missing-link-fragments` with ESQuery selector
  src/rules/no-missing-link-fragments.js
  tests/rules/no-missing-link-fragments.test.js
Labels: accepted, chore

#507 feat: expose identifiers in messages for no-empty-definitions
  src/rules/no-empty-definitions.js
  tests/rules/no-empty-definitions.test.js
Labels: accepted, feature, contributor pool

#506 feat: Expose identifiers in messages for no-duplicate-definitions
  src/rules/no-duplicate-definitions.js
  tests/rules/no-duplicate-definitions.test.js
Labels: accepted, feature, contributor pool

#508 refactor: correct no-reversed-media-syntax selectors
  src/rules/no-reversed-media-syntax.js
Labels: accepted, chore

#491 fix: improve no-html rule's tag location reporting
  src/rules/no-html.js
  tests/rules/no-html.test.js
Labels: bug, accepted, contributor pool

#510 build: add `prettier` to `update-rules-docs` script
  .prettierignore
  README.md
  tools/update-rules-docs.js
Labels: accepted, build

#511 refactor: simplify `no-bare-urls` with ESQuery selector
  src/rules/no-bare-urls.js
  src/util.js
  tests/rules/no-bare-urls.test.js
Labels: accepted, chore
