Repository eslint/markdown, pull requests merged in 2025-04, with the labels that each got.

#333 feat: export `MarkdownRuleDefinition` type
  src/index.js
  tests/types/types.test.ts
Labels: feature

#328 feat: support front matter
  README.md
  package.json
  src/language/markdown-language.js
  src/types.ts
  tests/language/markdown-language.test.js
Labels: accepted, feature, contributor pool

#332 feat: support `eslint` config comments
  src/language/markdown-source-code.js
  tests/language/markdown-source-code.test.js
Labels: accepted, feature, contributor pool

#338 chore: add docs url to all rules
  eslint.config.js
  src/rules/fenced-code-language.js
  src/rules/heading-increment.js
  src/rules/no-duplicate-headings.js
  src/rules/no-empty-links.js
  src/rules/no-html.js
  src/rules/no-invalid-label-refs.js
  src/rules/no-missing-label-refs.js
Labels: chore

#336 fix: replace `IMarkdownSourceCode` with `MarkdownSourceCode`
  package.json
  rollup.config.js
  src/index.js
  src/language/markdown-source-code.js
  src/types.ts
  tests/types/types.test.ts
Labels: bug, accepted, contributor pool

#342 docs: fix inaccurate description in `no-html.md`
  docs/rules/no-html.md
Labels: accepted, documentation

#334 feat: add missing `mdast` types to `MarkdownRuleVisitor`
  package.json
  src/types.ts
  tests/types/types.test.ts
Labels: accepted, feature, contributor pool

#344 fix: enhance fenced code language rule to support tilde as a delimiter
  src/rules/fenced-code-language.js
  tests/rules/fenced-code-language.test.js
Labels: bug, accepted, contributor pool

#345 chore: bump `@eslint/core` and `@eslint/plugin-kit` to latest
  package.json
Labels: accepted, chore

#347 test: correct `path` typos in `markdown-language.test.js`
  tests/language/markdown-language.test.js
Labels: accepted, chore

#348 fix: `no-missing-label-refs` rule does not respect escaping
  src/rules/no-missing-label-refs.js
  tests/rules/no-missing-label-refs.test.js
Labels: bug, accepted, contributor pool

#351 chore: replace chai with node.js assert
  package.json
  tests/examples/all.test.js
  tests/plugin.test.js
  tests/processor.test.js
Labels: accepted, chore, contributor pool
