Repository eslint/markdown, pull requests merged in 2025-07, with the labels that each got.

#465 fix: case-insensitive attribute checks in `no-missing-link-fragment`
  src/rules/no-missing-link-fragments.js
  tests/rules/no-missing-link-fragments.test.js
Labels: bug, accepted

#462 fix: remove unused types from `types.ts`
  src/types.ts
Labels: bug, accepted

#471 refactor: use `CustomRuleDefinitionType` in `MarkdownRuleDefinition`
  package.json
  src/types.ts
Labels: accepted, chore

#454 feat: add frontmatterTitle option to heading-increment
  docs/rules/heading-increment.md
  src/rules/heading-increment.js
  src/rules/no-multiple-h1.js
  src/util.js
  tests/rules/heading-increment.test.js
  tests/util.test.js
Labels: accepted, feature, contributor pool

#487 fix: fenced-code-language highlights only relevant parts
  src/rules/fenced-code-language.js
  tests/rules/fenced-code-language.test.js
Labels: bug, accepted, contributor pool
