Repository eslint/markdown, pull requests merged in 2025-09, with the labels that each got.

#490 feat: fix false positives and negatives for consecutive backslashes
  src/rules/no-missing-atx-heading-space.js
  src/rules/no-missing-label-refs.js
  src/rules/no-reversed-media-syntax.js
  tests/rules/no-missing-atx-heading-space.test.js
  tests/rules/no-missing-label-refs.test.js
  tests/rules/no-reversed-media-syntax.test.js
Labels: bug, accepted, feature

#519 chore: update eslint-config-eslint
  package.json
Labels: chore

#433 feat: add no-reference-like-urls rule
  README.md
  docs/rules/no-reference-like-urls.md
  src/rules/no-reference-like-urls.js
  tests/rules/no-reference-like-urls.test.js
Labels: accepted, feature, contributor pool

#520 feat: export types from main entry point
  src/index.js
  src/types.js
  tests/types/types.test.ts
Labels: accepted, feature

#523 fix: handle consecutive backslashes in `no-reference-like-urls`
  src/rules/no-reference-like-urls.js
  tests/rules/no-reference-like-urls.test.js
Labels: bug

#524 fix: `exactOptionalPropertyTypes` causes type errors when using plugins
  src/index.js
  tests/types/tsconfig.json
Labels: bug

#525 fix: report locations with <CR> linebreaks in `no-reference-like-urls`
  src/rules/no-reference-like-urls.js
  tests/rules/no-reference-like-urls.test.js
Labels: bug, accepted

#527 test: add package exports test
  tests/package/exports.test.js
  tests/types/tsconfig.json
Labels: accepted, chore, contributor pool

#376 feat: add support for `getLocFromIndex` and `getIndexFromLoc`
  package.json
  tests/language/markdown-source-code.test.js
  tests/types/types.test.ts
Labels: accepted, feature, Stale

#538 feat: export `MarkdownLanguage` from `index.js`
  src/index.js
  tests/package/exports.test.js
Labels: accepted, feature

#542 refactor: use `getLocFromIndex` in `no-multiple-h1`
  src/rules/no-multiple-h1.js
Labels: chore
