Repository eslint/markdown, pull requests merged in 2025-05, with the labels that each got.

#354 docs: Update README to use defineConfig
  README.md
Labels: documentation

#356 refactor: switch MarkdownSourceCode to extend TextSourceCodeBase
  package.json
  src/language/markdown-source-code.js
  src/types.ts
  tests/types/types.test.ts
Labels: accepted, chore, contributor pool

#352 chore: update ESLint config file to use `defineConfig`
  eslint.config.js
  package.json
Labels: accepted, chore

#357 feat: create `no-empty-images`
  README.md
  docs/rules/no-empty-images.md
  src/rules/no-empty-images.js
  tests/rules/no-empty-images.test.js
Labels: accepted, feature, contributor pool

#362 chore: add `*.code-workspace` to `.gitignore`
  .gitignore
Labels: chore

#363 ci: add test for `bun`
  .github/workflows/bun-test.yml
Labels: build

#375 docs: update README.md to mention linting Markdown
  README.md
Labels: accepted, documentation

#364 feat: add no-empty-definitions rule
  README.md
  docs/rules/no-empty-definitions.md
  src/rules/no-empty-definitions.js
  tests/rules/no-empty-definitions.test.js
Labels: accepted, feature, contributor pool

#379 build: Generate social media changelog
  .github/workflows/release-please.yml
Labels: accepted, build

#366 fix: `no-invalid-label-refs` do not report correct position
  src/rules/no-invalid-label-refs.js
  tests/rules/no-invalid-label-refs.test.js
Labels: bug, accepted

#381 docs: fix some typos
  docs/rules/fenced-code-language.md
  docs/rules/heading-increment.md
  docs/rules/no-html.md
Labels: accepted, documentation

#382 docs: update examples for rules
  docs/rules/fenced-code-language.md
  docs/rules/heading-increment.md
  docs/rules/no-duplicate-headings.md
  docs/rules/no-empty-definitions.md
  docs/rules/no-empty-images.md
  docs/rules/no-empty-links.md
  docs/rules/no-html.md
  docs/rules/no-invalid-label-refs.md
  docs/rules/no-missing-label-refs.md
Labels: documentation

#360 feat: create `no-duplicate-definitions`
  README.md
  docs/rules/no-duplicate-definitions.md
  src/rules/no-duplicate-definitions.js
  tests/rules/no-duplicate-definitions.test.js
Labels: accepted, feature

#385 fix: update `require-alt-text` rule to ignore commented images
  src/rules/require-alt-text.js
  tests/rules/require-alt-text.test.js
Labels: bug, accepted
